[package]
name = "refinement"
version = "0.1.0"
authors = ["Brady Dean <2bdkid@gmail.com>"]
edition = "2018"
description = "Convenient creation of type-safe refinement types."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
